<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EmployeList.aspx.cs" Inherits="GTI.Especiales.Aprendizaje.Client.EmployeList" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <section>
        <div>
            <hgroup>
                <h2><%: Page.Title %></h2>
            </hgroup>

            <div style="display:grid; grid-template-columns:1fr 1fr">
               <asp:DropDownList id="ColorList"
                    AutoPostBack="True"
                    runat="server"
                   class="btn-group">
                  <asp:ListItem Selected="True" Value="White" class="btn btn-primary dropdown-toggle"> Mostrar </asp:ListItem>
                  <asp:ListItem Value="Silver"> Activos </asp:ListItem>
               </asp:DropDownList>
                <div     class="text-right">
                    <button type="button" class="btn btn-outline-success" >
                        <asp:HyperLink NavigateUrl="~/" Text="Crear" runat="server"/>
                    </button>
                </div>
            </div>

            <br /><br />

            <asp:GridView runat="server" ID="employeList"
                ItemType="GTI.Especiales.Aprendizaje.Client.Models.Employe" DataKeyNames="EmployeID" 
                SelectMethod="GetEmployes"
                AutoGenerateColumns="false"
                UpdateMethod="EmployeGrid_UpdateItem" DeleteMethod="EmployeGrid_DeleteItem"
                AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" class="table">
                <Columns>
                    <asp:DynamicField DataField="EmployeID" />
                    <asp:DynamicField DataField="EmployeName" />
                    <asp:DynamicField DataField="RFC" />
                    <asp:DynamicField DataField="Salary" />    
                    <asp:DynamicField DataField="Active" /> 
                </Columns>
            </asp:GridView>

        </div>
    </section>
</asp:Content>
